services:
  - type: web
    name: cat-dog-classifier
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
